<?php

namespace Database\Seeders;

use App\Models\EquipTemplate;
use Illuminate\Database\Seeder;

class EquipTemplatesSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            $this->template([
                'id' => 'main_weapon_nanshan_t1_normal_01',
                'name' => '南山·主武·凡',
                'slot' => 'main_weapon',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'ATK',
                'main_min' => 18,
                'main_max' => 20,
                'white_stats' => ['ATK' => 20, 'HP' => 35],
                'star_growth' => ['ATK' => 4, 'HP' => 8],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'weapon',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_main_weapon_nanshan_t1_01',
                'upgrade_to_template_id' => 'main_weapon_nanshan_t1_high_01',
                'blueprint_item_id' => 'bp_weapon_nanshan_t1_01',
                'sort_order' => 10,
            ]),
            $this->template([
                'id' => 'main_weapon_nanshan_t1_high_01',
                'name' => '南山·主武·精',
                'slot' => 'main_weapon',
                'equip_type' => 'set',
                'rarity' => 'blue',
                'required_level' => 20,
                'main_stat' => 'ATK',
                'main_min' => 24,
                'main_max' => 26,
                'white_stats' => ['ATK' => 26, 'HP' => 42],
                'star_growth' => ['ATK' => 5, 'HP' => 10],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'weapon',
                'theme_key' => 'nanshan',
                'quality_tier' => 'high',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_main_weapon_nanshan_t1_01',
                'upgrade_from_template_id' => 'main_weapon_nanshan_t1_normal_01',
                'blueprint_item_id' => 'bp_weapon_nanshan_t1_01',
                'sort_order' => 11,
            ]),
            $this->template([
                'id' => 'off_weapon_nanshan_t1_normal_01',
                'name' => '南山·副武·凡',
                'slot' => 'off_weapon',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'ATK',
                'main_min' => 12,
                'main_max' => 14,
                'white_stats' => ['ATK' => 14, 'DEF' => 4],
                'star_growth' => ['ATK' => 3, 'DEF' => 1],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'weapon',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_off_weapon_nanshan_t1_01',
                'sort_order' => 20,
            ]),
            $this->template([
                'id' => 'armor_nanshan_t1_normal_01',
                'name' => '南山·盔甲·凡',
                'slot' => 'armor',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'DEF',
                'main_min' => 10,
                'main_max' => 12,
                'white_stats' => ['DEF' => 12, 'HP' => 65],
                'star_growth' => ['DEF' => 2, 'HP' => 14],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'armor',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_armor_nanshan_t1_01',
                'sort_order' => 30,
            ]),
            $this->template([
                'id' => 'belt_nanshan_t1_normal_01',
                'name' => '南山·腰带·凡',
                'slot' => 'belt',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'HP',
                'main_min' => 48,
                'main_max' => 52,
                'white_stats' => ['HP' => 52, 'DEF' => 4],
                'star_growth' => ['HP' => 12, 'DEF' => 1],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'armor',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_belt_nanshan_t1_01',
                'sort_order' => 40,
            ]),
            $this->template([
                'id' => 'shoes_nanshan_t1_normal_01',
                'name' => '南山·鞋子·凡',
                'slot' => 'shoes',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'DEF',
                'main_min' => 7,
                'main_max' => 9,
                'white_stats' => ['DEF' => 9, 'HP' => 30],
                'star_growth' => ['DEF' => 2, 'HP' => 8],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'armor',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_shoes_nanshan_t1_01',
                'sort_order' => 50,
            ]),
            $this->template([
                'id' => 'gloves_nanshan_t1_normal_01',
                'name' => '南山·护手·凡',
                'slot' => 'gloves',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'ATK',
                'main_min' => 8,
                'main_max' => 10,
                'white_stats' => ['ATK' => 10, 'HP' => 20],
                'star_growth' => ['ATK' => 2, 'HP' => 6],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'armor',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_gloves_nanshan_t1_01',
                'sort_order' => 60,
            ]),
            $this->template([
                'id' => 'helm_nanshan_t1_normal_01',
                'name' => '南山·头盔·凡',
                'slot' => 'helm',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'DEF',
                'main_min' => 8,
                'main_max' => 10,
                'white_stats' => ['DEF' => 10, 'HP' => 35],
                'star_growth' => ['DEF' => 2, 'HP' => 8],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'armor',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_helm_nanshan_t1_01',
                'sort_order' => 70,
            ]),
            $this->template([
                'id' => 'necklace_nanshan_t1_normal_01',
                'name' => '南山·项链·凡',
                'slot' => 'necklace',
                'equip_type' => 'set',
                'rarity' => 'white',
                'required_level' => 20,
                'main_stat' => 'HP',
                'main_min' => 30,
                'main_max' => 34,
                'white_stats' => ['HP' => 34, 'ATK' => 4],
                'star_growth' => ['HP' => 8, 'ATK' => 1],
                'star_cap' => 3,
                'set_id' => 'setline_kuangzhan_20',
                'set_line_id' => 'setline_kuangzhan',
                'set_stage' => 20,
                'flow_tag' => 'berserk',
                'slot_group' => 'accessory',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T1',
                'forge_family_id' => 'family_necklace_nanshan_t1_01',
                'sort_order' => 80,
            ]),
            $this->template([
                'id' => 'ring_nanshan_t2_normal_01',
                'name' => '南山·戒指·凡',
                'slot' => 'ring',
                'equip_type' => 'ring',
                'rarity' => 'blue',
                'required_level' => 40,
                'main_stat' => 'ATK',
                'main_min' => 10,
                'main_max' => 12,
                'white_stats' => ['ATK' => 12, 'CRIT_PERCENT' => 2],
                'star_growth' => ['ATK' => 2, 'CRIT_PERCENT' => 1],
                'star_cap' => 6,
                'flow_tag' => 'berserk',
                'slot_group' => 'accessory',
                'theme_key' => 'nanshan',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T2',
                'forge_family_id' => 'family_ring_nanshan_t2_01',
                'upgrade_to_template_id' => 'ring_nanshan_t2_high_01',
                'blueprint_item_id' => 'bp_ring_nanshan_t2_01',
                'sort_order' => 90,
            ]),
            $this->template([
                'id' => 'ring_nanshan_t2_high_01',
                'name' => '南山·戒指·精',
                'slot' => 'ring',
                'equip_type' => 'ring',
                'rarity' => 'purple',
                'required_level' => 40,
                'main_stat' => 'ATK',
                'main_min' => 14,
                'main_max' => 16,
                'white_stats' => ['ATK' => 16, 'CRIT_PERCENT' => 3],
                'star_growth' => ['ATK' => 3, 'CRIT_PERCENT' => 1],
                'star_cap' => 6,
                'flow_tag' => 'berserk',
                'slot_group' => 'accessory',
                'theme_key' => 'nanshan',
                'quality_tier' => 'high',
                'forge_enabled' => true,
                'forge_tier' => 'T2',
                'forge_family_id' => 'family_ring_nanshan_t2_01',
                'upgrade_from_template_id' => 'ring_nanshan_t2_normal_01',
                'blueprint_item_id' => 'bp_ring_nanshan_t2_01',
                'sort_order' => 91,
            ]),
            $this->template([
                'id' => 'bracelet_qingqiu_t2_normal_01',
                'name' => '青丘·手镯·凡',
                'slot' => 'bracelet',
                'equip_type' => 'bracelet',
                'rarity' => 'blue',
                'required_level' => 40,
                'main_stat' => 'DEF',
                'main_min' => 9,
                'main_max' => 11,
                'white_stats' => ['DEF' => 11, 'HP' => 42],
                'star_growth' => ['DEF' => 2, 'HP' => 10],
                'star_cap' => 6,
                'flow_tag' => 'frost',
                'slot_group' => 'accessory',
                'theme_key' => 'qingqiu',
                'quality_tier' => 'normal',
                'forge_enabled' => true,
                'forge_tier' => 'T2',
                'forge_family_id' => 'family_bracelet_qingqiu_t2_01',
                'upgrade_to_template_id' => 'bracelet_qingqiu_t2_high_01',
                'blueprint_item_id' => 'bp_bracelet_qingqiu_t2_01',
                'sort_order' => 100,
            ]),
            $this->template([
                'id' => 'bracelet_qingqiu_t2_high_01',
                'name' => '青丘·手镯·精',
                'slot' => 'bracelet',
                'equip_type' => 'bracelet',
                'rarity' => 'purple',
                'required_level' => 40,
                'main_stat' => 'DEF',
                'main_min' => 13,
                'main_max' => 15,
                'white_stats' => ['DEF' => 15, 'HP' => 50],
                'star_growth' => ['DEF' => 3, 'HP' => 12],
                'star_cap' => 6,
                'flow_tag' => 'frost',
                'slot_group' => 'accessory',
                'theme_key' => 'qingqiu',
                'quality_tier' => 'high',
                'forge_enabled' => true,
                'forge_tier' => 'T2',
                'forge_family_id' => 'family_bracelet_qingqiu_t2_01',
                'upgrade_from_template_id' => 'bracelet_qingqiu_t2_normal_01',
                'blueprint_item_id' => 'bp_bracelet_qingqiu_t2_01',
                'sort_order' => 101,
            ]),
            $this->template([
                'id' => 'talisman_shop_40_01',
                'name' => '宗门护符·壹',
                'slot' => 'talisman',
                'equip_type' => 'talisman',
                'rarity' => 'purple',
                'required_level' => 40,
                'main_stat' => 'HP',
                'main_min' => 80,
                'main_max' => 90,
                'white_stats' => ['HP' => 90, 'QI' => 6],
                'star_growth' => ['HP' => 14, 'QI' => 1],
                'star_cap' => 6,
                'flow_tag' => 'universal',
                'slot_group' => 'accessory',
                'theme_key' => 'qingqiu',
                'quality_tier' => 'normal',
                'forge_enabled' => false,
                'forge_tier' => null,
                'forge_family_id' => 'family_talisman_shop_40_01',
                'sort_order' => 110,
            ]),
        ];

        foreach ($rows as $row) {
            EquipTemplate::query()->updateOrCreate(
                ['id' => $row['id']],
                $row,
            );
        }

        $validIds = array_map(fn (array $row): string => (string) $row['id'], $rows);
        EquipTemplate::query()
            ->whereNotIn('id', $validIds)
            ->delete();
    }

    private function template(array $row): array
    {
        return array_merge([
            'icon' => '',
            'set_id' => null,
            'set_line_id' => null,
            'set_stage' => null,
            'flow_tag' => null,
            'required_level' => 1,
            'white_stats' => [],
            'star_growth' => [],
            'star_enabled' => true,
            'star_cap' => 10,
            'can_attach_blue_affix' => true,
            'can_roll_purple_affix' => false,
            'socket_rule_ref' => 'auto_star_3_6_8_10',
            'slot_group' => null,
            'theme_key' => null,
            'quality_tier' => 'normal',
            'forge_enabled' => false,
            'forge_tier' => null,
            'forge_family_id' => null,
            'upgrade_from_template_id' => null,
            'upgrade_to_template_id' => null,
            'blueprint_item_id' => null,
            'effects' => [],
            'unidentified_chance' => 0,
            'is_enabled' => true,
            'sort_order' => 0,
        ], $row);
    }
}
