<?php

namespace Database\Seeders;

use App\Models\StoryChapter;
use Illuminate\Database\Seeder;

class StoryChaptersSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            $this->chapter(
                'chapter_nanshan_00',
                0,
                '南山一经',
                '鹊山将启',
                '序章',
                'map_quque_start',
                1,
                5,
                '山海失序，诸山封脉崩裂。巡山司重启旧制，命巡山使候补入山巡厄。自鹊山而始，旧日被遗忘的山海禁地，再度向人间敞开。',
                '完成巡山使候补试炼，辨认山印残痕，收拢鹊山外沿残散的封脉节点，为正式入山做准备。',
                '当鹊山残印被重新点亮时，你第一次感知到真正的山海异气。那不是寻常妖气，而是封脉断裂后泄出的“厄”。',
                '',
                '鹊山试炼既成，巡山司允许你携录入山。真正的南山巡厄，从招摇之山开始。',
                '沿着重新显现的山路向前，第一座回应山印的山域，正是南山之首招摇。',
                10,
            ),
            $this->chapter(
                'chapter_nanshan_01',
                1,
                '南山一经',
                '招摇之山',
                '主线',
                'map_zhaoyao',
                1,
                10,
                '南山之首，曰招摇。山中多桂，多金玉，祝余与迷榖本为安神定行之物，如今却随灵脉逆流一同躁动。连狌狌也开始脱离旧性，在林间聚群称王。',
                '平定招摇林脉躁动，采集桂木、祝余叶与迷榖枝，查清狌狌群为何会围绕山印聚集。',
                '白耳赤目的狌狌王已不再只是逐木而栖的异兽，它立于山印之前，像是在守着什么。',
                'boss_zhaoyao_xingxing',
                '狌狌王伏诛后，招摇外层林脉得以短时安稳。祝余与迷榖重新回应山气，但山印深处的裂痕仍在缓慢扩散。',
                '顺着裂痕延伸的木脉与矿脉冲突，下一处异动已指向堂庭之山。',
                20,
            ),
            $this->chapter(
                'chapter_nanshan_02',
                2,
                '南山一经',
                '堂庭之山',
                '主线',
                'map_tangting',
                10,
                20,
                '堂庭之山，棪木成林，水玉藏脉。原本栖于山中的白猿因灵泉浑浊而性情大变，整片山域的木脉与矿脉正在互相冲撞。若堂庭失守，南山外层的灵材供给将彻底断绝。',
                '疏导堂庭灵泉与矿脉冲突，收集棪木与水玉晶，调查白猿王与矿泉浑浊的根由。',
                '堂庭白猿王踏着碎裂的矿脉而来，毛色尽染灰尘与浊泉，它已将整片山谷当作自己的领地。',
                'boss_tangting_ape',
                '堂庭矿泉重归清亮，外层灵材供给得以保住，但浑浊之源并未来自山内，而是被更深处的裂脉逼出。',
                '白玉与毒雾交缠的猨翼之山，正在成为封脉裂痕最清晰的显化之地。',
                30,
            ),
            $this->chapter(
                'chapter_nanshan_03',
                3,
                '南山一经',
                '猨翼之山',
                '主线',
                'map_yuanyi',
                20,
                30,
                '猨翼之山，白玉深藏，蝮虫与怪蛇密布。此地毒雾终年不散，草木稀绝，寻常行者难以近山。如今山中异气更盛，封脉断裂的痕迹第一次清晰可见。',
                '深入毒雾区查验封脉裂缝，收集白玉髓与毒瘴结晶，查明蝮王为何盘踞在裂脉源头。',
                '雾海深处，蝮王借裂脉异气盘身而立，毒雾随其吐息涌动，像在替某个更大的意志守门。',
                'boss_yuanyi_viper',
                '蝮王陨落后，裂脉显露出更古老的矿脉纹路。你确认，南山外层的崩裂并非单点异变，而是成片连锁。',
                '顺着赤金与白金翻涌的矿脉痕迹，下一站只能是杻阳之山。',
                40,
            ),
            $this->chapter(
                'chapter_nanshan_04',
                4,
                '南山一经',
                '杻阳之山',
                '主线',
                'map_niuyang',
                30,
                40,
                '杻阳之山，多赤金，多白金。鹿蜀奔走山野，旋龟守于深泽，本是南山中最稳的一处矿脉山域。如今矿脉翻涌、兽群逆行，连守脉之兽也开始出现异化征兆。',
                '平衡杻阳矿潮，分别追查鹿蜀与旋龟的失控源头，收集赤金砂、白金砂与旋龟甲片。',
                '赤尾鹿蜀王踏碎矿道而来，背后更能听见深泽之中旋龟守脉者拍击水面的回响。杻阳已不只是矿脉失控。',
                'boss_niuyang_lushu',
                '杻阳主矿重新归稳，鹿蜀与旋龟留下的守脉线索却都指向更深层的异化源。南山底层秩序开始松脱。',
                '柢山裂渊传来的潮鸣与骨啸，已说明真正的崩解在更深处。',
                50,
            ),
            $this->chapter(
                'chapter_nanshan_05',
                5,
                '南山一经',
                '柢山裂渊',
                '主线',
                'map_dishan',
                40,
                50,
                '柢山多水而无草木，荒冷得不似人间山域。裂谷之下，旧日沉寂的异种开始成群浮现。这里已不是单纯封印松动后的兽潮，而是南山底层秩序本身正在瓦解。',
                '深入裂渊底层，击退异种潮，搜集裂渊石与鯥羽鳞，确认深层封脉的破损范围。',
                '裂渊深处，鯥王自黑水之中抬首，整片谷底的水压与灵压都随之转向。它像是裂渊意志本身。',
                'boss_dishan_lu',
                '柢山裂渊暂时沉寂，但最核心的封脉并不在此。你只是在裂渊底部，看见了通往禁山与终章的入口。',
                '巡山司命你分赴亶爰秘禁与基山秘藏，分别寻回禁山记录与续脉所需灵晶。',
                60,
            ),
            $this->chapter(
                'chapter_nanshan_06',
                6,
                '南山一经',
                '亶爰秘禁',
                '功能区',
                'map_tanyuan',
                40,
                55,
                '亶爰之山，不生草木，不容常行。这里从来不是供人征服的山，而是被封起来等待遗忘的地方。如今禁门松裂，巡山司不得不重新记录它的名字。',
                '重新勘定秘禁山门、取回禁录残页与旧印，压制禁山外泄的古禁异气。',
                '被称为“类”的古老守禁异种自裂门后现身，它并非单纯兽类，更像是古禁意志的躯壳。',
                'boss_tanyuan_lei',
                '秘禁山门重新闭合，巡山司得以补全失落的亶爰档案。你也确认，青丘之前仍缺最后一把续脉的钥匙。',
                '下一步需前往基山秘藏，取回能与山印相合的灵晶。',
                70,
            ),
            $this->chapter(
                'chapter_nanshan_07',
                7,
                '南山一经',
                '基山秘藏',
                '功能区',
                'map_jishan',
                45,
                58,
                '基山藏玉，也藏着比玉更古老的东西。山中异矿在灵脉逆流下凝成新的结晶，古兽与异鸟盘踞秘藏之所，守着不属于这个时代的灵性碎片。若能取回这些灵晶，便能将山海之力嵌入兵甲。',
                '收集秘藏灵晶、稳住异矿潮汐，取得可用于续封脉与兵甲嵌灵的关键结晶。',
                '秘藏最深处，猼訑自矿光中缓步走出，像是在挑选谁有资格带走基山留下的古老灵性。',
                'boss_jishan_boti',
                '基山灵晶到手，兵甲嵌灵与终章续脉的条件都已凑齐。巡山司将你正式派往青丘。',
                '青丘与箕尾的封尾之战，已无回避余地。',
                80,
            ),
            $this->chapter(
                'chapter_nanshan_08',
                8,
                '南山一经',
                '青丘封尾',
                '终章',
                'map_qingqiu',
                50,
                60,
                '青丘之山，玉出其间，灌灌飞鸣，赤鱬潜游。这里本应是南山最灵秀的一段山域，如今却被妖雾与异光笼罩。所有断裂的封脉，最后都指向了这里。',
                '击破青丘外围妖雾、压制灌灌与赤鱬异化波动，寻回箕尾续封脉所需的最后封符与镇印。',
                '青丘深处的九尾妖影并非单一异兽，而是整片青丘失序意志汇成的终章化身。箕尾封脉守影也已在更深处苏醒。',
                'boss_qingqiu_nine_tail',
                '九尾妖影散去后，青丘主脉终于重新显形。剩下的最后一步，是在箕尾之山完成续封脉。',
                '携青丘封符前往箕尾之山，重立镇印，南山一经方能真正封尾。',
                90,
            ),
        ];

        foreach ($rows as $row) {
            StoryChapter::query()->updateOrCreate(
                ['chapter_id' => $row['chapter_id']],
                $row,
            );
        }
    }

    private function chapter(
        string $chapterId,
        int $chapterNo,
        string $volumeName,
        string $chapterName,
        string $chapterRole,
        ?string $mapId,
        int $levelMin,
        int $levelMax,
        string $introCopy,
        string $objectiveCopy,
        string $bossIntroCopy,
        ?string $bossId,
        string $clearCopy,
        string $nextHookCopy,
        int $sortOrder,
    ): array {
        return [
            'chapter_id' => $chapterId,
            'volume_name' => $volumeName,
            'chapter_no' => $chapterNo,
            'chapter_name' => $chapterName,
            'chapter_role' => $chapterRole,
            'map_id' => $mapId,
            'level_min' => $levelMin,
            'level_max' => $levelMax,
            'intro_copy' => $introCopy,
            'objective_copy' => $objectiveCopy,
            'boss_intro_copy' => $bossIntroCopy,
            'boss_id' => $bossId,
            'clear_copy' => $clearCopy,
            'next_hook_copy' => $nextHookCopy,
            'icon_path' => '',
            'banner_path' => '',
            'sort_order' => $sortOrder,
            'is_enabled' => true,
        ];
    }
}
